### ISSUE TITLE
i try to crypt my app

### ISSUE THREAD

**Issue by tarekxxx** [TalosSec/Cronos-Crypter#2]
but funcation not working at all

**Comment by Aries52** [comment]
> 

What do you mean by "funcation not working at all", please specify your error

**Comment by XaFF-XaFF** [comment]
Error not specified.

**Comment by tarekxxx** [comment]
whole funcation my application not working after this plus my program become more detected then before your crypter + damge my funcation in program

**Comment by XaFF-XaFF** [comment]
> whole funcation my application not working after this plus my program become more detected then before your crypter + damge my funcation in program

In what language is your app written? What's an extension of your app and what's it's architecture?
