### ISSUE TITLE
Nice try 

### ISSUE THREAD

**Issue by TigerMates** [TalosSec/Cronos-Crypter#3]
Thanks for use our program buddy 
just give us Credit the real author

**Comment by XaFF-XaFF** [comment]
lmao

**Comment by Aries52** [comment]
"Your" program doesn't even have sourcecode properly made, also your commits are like:
Changed "Authors: XaFF, Ajajjajk" to "Authors: TigerMate" so I think that you could leave this discussion and stop making fun of yourself. Thanks
